server:
  port: 8085
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dong?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.mybatisdemo01.entity
#showSql
logging:
  level:
    com:
      example:
        mybatisdemo01:
          mapper: debug